services:
  loginjwt-be:
    image: ${DOCKER_REGISTRY-}loginjwtbe
    build:
      context: .
      dockerfile: LoginJWT-be/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - loginjwt-network
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Bagdad#12
    ports:
      - "1433:1433"
    volumes:
      - ./.containers/database:/var/opt/mssql/data
    networks:
      - loginjwt-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Bagdad#12" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

networks:
  loginjwt-network:
    driver: bridge
